version: 2.1

workflows:
  test-build:
    jobs:
      - build

jobs:
  build: 
    docker:
      - image: cimg/node:16.6.2
    steps:
      - checkout
      - run: 
          name: "Set variable"
          command: echo "Hello $NAME"
          environment: 
            NAME: "Emran"
      - run:
          name: "get variable"
          command: echo "Hello $NAME"