version: 2.1

workflows:
  test-build:
    jobs:
      - build

jobs:
  build: 
    docker:
      - image: cimg/node:16.6.2
    steps:
      - checkout
      - run: node --version
      - run: 
          name: "1st run"
          command: |
            echo 'export PATH=/max/home' >> $BASH_ENV
            source $BASH_ENV
            echo "$BASH_ENV"
            echo "ENV is $PATH"
      - run: echo "env is $PATH"
      - run: 
          name: "Install depandance"
          command: npm  install
      - run:
          name: "Run test"
          command: "npm run test"